### ISSUE TITLE
Make turtles move without leaving a trail

### ISSUE THREAD

**Issue by elenam** [clojurebridge-boston/track1-turtles#17]

**Comment by elenam** [comment]
A turtle color can now be turned to `:white`. This makes the turtle move on the white canvas without leaving a trail. Would cross over other lines, though. 
Need a better solution eventually.

**Comment by jsa-aerial** [comment]
I thought there was a way to erase the lines. Seems that's how we moved them in practice - move them then erase line. If so, maybe have a separate move and draw, where move just erases as last action.

**Comment by elenam** [comment]
There is "home", it brings the turtle back to center. 
https://github.com/elenam/track1-turtles/blob/master/outline/TURTLE.md (not updated yet for our recent changes)

**Comment by elenam** [comment]
@jsa-aerial Never mind, you are right, there is `clean`.

**Comment by elenam** [comment]
I will close this issue for now. We might want to revisit it later.
