### ISSUE TITLE
Use color names, not rgb values

### ISSUE THREAD

**Issue by elenam** [clojurebridge-boston/track1-turtles#19]

**Comment by elenam** [comment]
What kind of things should these be? We can define a bunch of variables, but that may get confusing because turtle names are keywords. We could use keywords to look up colors in a map (and add-turtle and set-color can check if what's passed is a keyword).

**Comment by elenam** [comment]
Colors should be variables, not keywords, so that we can compare them using =.

**Comment by jsa-aerial** [comment]
What? = works fine with keywords. Variables is a really bad idea. The idea of using a map with color keyword keys (:red, :blue, etc) to the values needed seems like the simplest way to go.

**Comment by elenam** [comment]
You can't make a keyword work like a color, so :red would never be equal to the rgb value for red. You wouldn't be able to use it in filter, say.

**Comment by elenam** [comment]
Or it would require a very significant rewrite.

**Comment by elenam** [comment]
@jsa-aerial Colors in the state (as returned to the user) are represented as keywords when they have names, and as rgb vectors when they don't. They are always represented as rgb vectors internally. When the `state` function is called , a reverse lookup is done to print names if exist. This allows us to do search by color names or by rgbs, although we might also want to define a `color=?` function, in case someone wants to look for red by its rgb value.
